GRAY_ENCODING = 'gray'
BIN_ENCODING = 'bin'
ENCODINGS = (GRAY_ENCODING, BIN_ENCODING)

UNIFORM_INIT = ('uniform', 'Uniform')
INITS = (UNIFORM_INIT,)

RWS_SEL = ('rws', 'RWS')
TOURNAMENT_2_SEL = ('tournament_2', 'Tournament 2')
TOURNAMENT_4_SEL = ('tournament_4', 'Tournament 4')
TOURNAMENT_12_SEL = ('tournament_12', 'Tournament 12')
SUS_SEL = ('sus', 'SUS')
SEL_TYPES = (
    RWS_SEL,
    TOURNAMENT_2_SEL,
    TOURNAMENT_4_SEL,
    TOURNAMENT_12_SEL,
    SUS_SEL,
)

TOURNAMENT_SEL_GROUP = (
    TOURNAMENT_2_SEL,
    TOURNAMENT_4_SEL,
    TOURNAMENT_12_SEL,
)

ACKLEYS_FUNC = ('ackleys', 'Ackleys')
DEBS_FUNC = ('debs', 'Debs')
GRIWANGKS_FUNC = ('griwangks', 'Griwangks')
RASTRIGINS_FUNC = ('rastrigins', 'Rastrigins')
SCHWEFELS_FUNC = ('schwefels', 'Schwefels')
SPHERICAL_FUNC = ('spherical', 'Spherical')
UNEVEN_DEBS_FUNC = ('uneven_debs', 'Uneven_debs')

ESTIMS = (
    ACKLEYS_FUNC,
    DEBS_FUNC,
    GRIWANGKS_FUNC,
    RASTRIGINS_FUNC,
    SCHWEFELS_FUNC,
    SPHERICAL_FUNC,
    UNEVEN_DEBS_FUNC,
)

TESTING_FACTORS = (0.8, 1, 1.2)

DEFAULT_TRY_NUM = 15

CREATE_EXP_SUITE_TASK = ('CREATE_EXP_SUITE', 'CREATE_EXP_SUITE Task')
PROCESS_TEST_SUITE_TASK = ('PROCESS_TEST_SUITE', 'PROCESS_TEST_SUITE Task')
FINALIZE_TEST_SUITE_TASK = ('FINALIZE_TEST_SUITE', 'FINALIZE_TEST_SUITE Task')
PROCESS_RUN_SET_TASK = ('PROCESS_RUN_SET', 'PROCESS_RUN_SET Task')
FINALIZE_RUN_SET_TASK = ('FINALIZE_RUN_SET', 'FINALIZE_RUN_SET Task')

TASKS = (
    CREATE_EXP_SUITE_TASK,
    PROCESS_TEST_SUITE_TASK,
    FINALIZE_TEST_SUITE_TASK,
    PROCESS_RUN_SET_TASK,
    FINALIZE_RUN_SET_TASK,
)
